apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c2uakx1la-nodejs
  janus-idp.io/tekton: c2uakx1la-nodejs
  backstage.io/kubernetes-id: c2uakx1la-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c2uakx1la-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
